== Микросервисы

Source: link:https://microservices.io/patterns/microservices.html[]

=== 1) Зачем оно вам (микросервисы)?

1. Над приложением работает команда разработчиков
2. Новые члены команды должны быстро стать продуктивными
3. Приложение должно быть простым для понимания и изменения
4. Вы хотите практиковать непрерывное развертывание приложения
5. Вы должны запускать несколько экземпляров приложения на нескольких компьютерах, чтобы удовлетворить требования масштабируемости и доступности.
6. Вы хотите использовать новые технологии (фреймворки, языки программирования и т. д.)

=== 2) Преимущества микросервисов - part1

1. Высокая ремонтопригодность и возможность тестирования — обеспечивает быструю и частую разработку и развертывание.
2. Слабо связанный с другими сервисами — позволяет команде большую часть времени работать независимо над своими сервисами, не подвергаясь влиянию изменений в других сервисах и не влияя на другие сервисы.
3. Возможность независимого развертывания — позволяет команде развертывать свой сервис без необходимости координировать свои действия с другими командами.
4. Возможность разработки небольшой командой, необходимая для высокой производительности за счет избегания высококоммуникативного руководителя больших команд.

==== 2.1) Преимущества микросервисов - part2 (расширенная)

1. Обеспечивает непрерывную доставку и развертывание больших и сложных приложений.
- 1) Улучшенная ремонтопригодность — каждый сервис относительно небольшой, поэтому его легче понять и изменить.
- 2) Лучшая тестируемость — сервисы меньше по размеру и быстрее тестируются
- 3) Улучшенная развертываемость — сервисы можно развертывать независимо +
Это позволяет вам организовать усилия по разработке вокруг нескольких автономных команд. Каждая (так называемая «две пиццы») команда владеет и отвечает за один или несколько сервисов. Каждая команда может разрабатывать, тестировать, развертывать и масштабировать свои сервисы независимо от всех других команд.
2. Каждый микросервис относительно мал:
- 1) Легче понять разработчику
- 2) IDE работает быстрее, делая разработчиков более продуктивными
- 3) Приложение запускается быстрее, что повышает продуктивность разработчиков и ускоряет развертывание.
3. Улучшенная изоляция неисправностей. Например, если в одной службе есть утечка памяти, то затронута будет только эта служба. Другие службы продолжат обрабатывать запросы. Для сравнения, один неисправный компонент монолитной архитектуры может вывести из строя всю систему.
4. Устраняет любые долгосрочные обязательства перед стеком технологий. При разработке нового сервиса вы можете выбрать новый стек технологий. Точно так же при внесении серьезных изменений в существующую службу вы можете переписать ее, используя новый стек технологий.

=== 3) Недостатки микросервисов

1. Разработчикам приходится сталкиваться с дополнительной сложностью создания распределенной системы:
- 1) Разработчики должны внедрить механизм межсервисной связи и справиться с частичным сбоем.
- 2) Реализация запросов, охватывающих несколько сервисов, сложнее.
- 3) Тестировать взаимодействие между сервисами сложнее
- 4) Выполнение запросов, охватывающих несколько сервисов, требует тщательной координации между командами.
- 5) Инструменты разработчика/IDE ориентированы на создание монолитных приложений и не предоставляют явной поддержки для разработки распределенных приложений.
2. Сложность развертывания. В производственной среде также существует операционная сложность развертывания и управления системой, состоящей из множества различных сервисов.
3. Повышенное потребление памяти. Архитектура микросервисов заменяет N экземпляров монолитных приложений NxM экземплярами сервисов. Если каждая служба работает в своей собственной JVM (или ее эквиваленте), что обычно необходимо для изоляции экземпляров, то накладные расходы в M раз превышают количество сред выполнения JVM. Более того, если каждый сервис работает на собственной виртуальной машине (например, экземпляре EC2), как в случае с Netflix, накладные расходы еще выше.