== OSS vs BSS

link:https://wisdomplexus.com/blogs/oss-bss-architecture-explained/[wisdomplexus.com]

=== 1. OSS

OSS (Operational Support Systems) отвечает за работу коммуникационных сетей.

*_Особенности OSS_*:

- Есть система управления ошибками.
- Обеспечивает оверлейную сеть. Overlay Network - это любая сеть, построенная "поверх" другой (отсюда и overlay). Частный случай - VPN.
- Управление заявками на услуги.
- Конфигурация сети выполняется OSS.
- Есть системы предоплаты и постоплаты.
- OSS имеет собственную систему управления базами данных.

=== 2. BSS

BSS (Business Support Systems) описывает проблемы бизнеса или клиентов в функциональных возможностях. Например, существуют различные инструменты BSS, которые могут помочь улучшить качество обслуживания клиентов, создавая новые предложения и выставляя счета. Мы также используем BSS для связи между различными сетями.

Этот программный инструмент обычно используется для управления всеми бизнес-операциями путем их организации. Однако совместно OSS и BSS могут создать эффективную и надежную сетевую услугу для клиентов.

*_Особенности БСС_*:

- Управление заказами клиентов.
- Поддержка управления продуктами.
- Он отслеживает Subscription model и управляет ею.
- Имеет собственную Billing-систему.