=== Внедрение зависимостей через поле

Третья разновидность внедрения зависимостей, поддерживаемая в Spring, называется внедрением зависимостей через поле. Как подразумевает само название, зависимость внедряется непосредственно в поле, и для этой цели не требуется ни конструктор, ни метод установки, достаточно лишь снабдить аннотацией *_@Autowired_* соответствующее поле, являющееся членом класса.

[source,java]
----
@Service("singer")
public class Singer {
  @Autowired
  private Inspiration inspirationBean;

  public void sing() {
    System.out.println(inspirationBean.getLyric());
  }
}
----

Поле _inspirationBean_ объявлено закрытым, хотя это не имеет никакого значения для *_контейнера инверсии уnравления_*, nоскольку для заnолнения обязательной зависимости в нем nрименяется рефлексия.

Внедрению зависимостей через поле присущи перечисленные ниже недостатки, поэтому его обычно принято избегать:

- Несмотря на всю простоту такого способа внедрения зависимостей, необходимо соблюдать особую осторожность, чтобы не нарушить *_принцип единственной ответственности_*. Чем больше зависимостей, тем больше обязанностей у класса, а это может затруднить разделение обязанностей во время реорганизации кода. Ситуацию, когда класс становится слишком громоздким, легче выявить, когда зависимости внедряются через конструкторы или методы установки, но довольно трудно обнаружить, когда они внедряются через поля.
- В каркасе Spring обязанности по внедрению зависимостей передаются контейнеру инверсии управления, но класс должен явно сообщить типы требующихся зависимостей через открытый интерфейс, методы или конструкторы. Если же зависимости внедряются через поля, то может быть неясно, зависимость какого именно типа требуется и является ли она обязательной или нет.
- Внедрение зависимостей через поле вносит *_зависимость от контейнера инверсии управления_*, поскольку аннотация @Autowired является компонентом Spring. Следовательно, компонент Spring Bean больше не является *_простым объектом POJO_*, и его экземпляр нельзя получить независимым путем.
- Внедрение зависимостей через поле неприменимо к final полям. Такие поля могут быть инициализированы только с помощью внедрения зависимостей через конструктор.
- Внедрение зависимостей через поле затрудняет написание тестов, поскольку зависимости приходится внедрять вручную.



