=== Contexts hierarchy

В Spring поддерживается иерархическая структура для интерфейса ApplicationContext, когда один контекст (и связанная с ним фабрика типа BeanFactory) является родительским для другого контекста. Разрешая вложение контекста типа ApplicationContext, каркас Spring делает возможным разнесение конфигурации по отдельным файлам.

При вложении контекста типа *_ApplicationContext_* каркас Spring позволяет компонентам Spring Beans из порожденного контекста ссылаться на компоненты в *_родительском_* контексте. *_Вложение_* контекста типа ApplicationContext с помощью класса *_GenericXmlApplicationContext_* осуществляется очень просто. Чтобы вложить один контекст типа GenericXmlApplicationContext в другой, достаточно вызвать метод *_setParent()_* в порожденном контексте типа ApplicationContext, как показано в следующем примере кода: _p128_contexts_hierarchy/HierarchicalAppContextUsage.java_

В файле конфигурации порожденного контекста типа ApplicationContext ссылка на какой-нибудь компонент Spring Bean из родительского контекста типа ApplicationContext действует таким же образом, как и ссылка на компонент Spring Bean из порожденного контекста типа ApplicationContext, если только в порожденном контексте данного типа не присутствует компонент Spring Bean с тем же самым именем. В таком случае необходимо просто заменить атрибут bean в дескрипторе <ref> атрибутом parent.

В компоненте songЗ дескриптор разметки <ref> служит для ссылки на компонент childTi tle непосредственно из родительского контекста типа Application Context. Но поскольку в этом компоненте применяется атрибут parent из дескриптора разметки <ref>, то экземпляр компонента childTi tle, объявленный в порожденном контексте типа ApplicationContext, полностью игнорируется. Смотри _p128_contexts_hierarchy/child.xml_
