=== Spring – Injecting Collections

==== Baeldung guide:

link:https://www.baeldung.com/spring-injecting-collections[link] +
We're going to show how to inject Java collections using the Spring framework. Simply put, we'll demonstrate examples with the List, Map, Set collection interfaces. +
Кроме того, там есть ссылка на работу *_@Order_* с *_AspectJ_* - но она не очень. Лучше посмотреть на эту ссыль: link:https://jstobigdata.com/spring/advice-ordering-using-order-in-spring-aop/[jstobigdata] (там три *_@Aspect_* - ZeroAdvice.java, SecondAdvice.java, ThirdAdvice.java)


==== List With @Autowired

*_See_* _p131_injecting_collections/autowire_collection/CollectionsBean.java_, _p131_injecting_collections/autowire_collection/CollectionConfig.java_

Here, we declared the *_nameList_* property to hold a List of String values. In this example, we use field injection for nameList. Therefore, we put the @Autowired annotation.

After, we register the CollectionsBean in the configuration setup class

==== Set With Constructor Injection

*_See_* _p131_injecting_collections/set_bean/SetBean.java_, _p131_injecting_collections/set_bean/SetConfig.java_

This time we want to use a constructor injection for initializing the nameSet property

==== Map With Setter Injection

*_See_* _p131_injecting_collections/map_bean/MapBean.java_, _p131_injecting_collections/map_bean/MapConfig.java_

This time we have a setter method in order to use a *_setter dependency injection_*

We use @Component to provide MapBean bean

==== Injecting Bean References

*_See_* _p131_injecting_collections/BaeldungBean.java_, _p131_injecting_collections/multiple_beans/BaeldungCollectionBean.java_, _p131_injecting_collections/multiple_beans/BaeldungBeanConfig.java_

We add the Java configuration factory methods for each BaeldungBean element. The Spring container injects the individual beans of the BaeldungBean type into one collection.

==== Using @Order to Sort Beans

*_See_* _p131_injecting_collections/multiple_ordered_beans/BaeldungBeanOrderConfig.java_, _p131_injecting_collections/multiple_ordered_beans/BaeldungCollectionBean.java_

We can specify the order of the beans while injecting into the collection.

For that purpose, we use the @Order annotation and specify the index

==== Using @Qualifier to Select Beans

*_See_* _p131_injecting_collections/multiple_qualified_beans/BaeldungBeanQualifierConfig.java_, _p131_injecting_collections/multiple_qualified_beans/BaeldungQualifierCollectionBean.java_

We can use the @Qualifier to select the beans to be injected into the specific collection that matches the @Qualifier name.
