=== Внедрение зависимостей через метод поиска

==== Baeldung guide:

link:https://www.baeldung.com/spring-lookup[link] for *_@Lookup_* annotation usage +
*_See_* @Lookup in _p141_di_via_lookup_method/SpecificLookupDemoBean.java_

==== Book:

Внедрение зависимостей через метод поиска было введено в версии Spring 1.1 для преодоления затруднений, возникающих в том случае, если один компонент Spring Bean зависит от другого компонента с *_отличающимся жизненным циклом_*, в частности, когда _Singleton_ объект зависит от _Prototype_ объекта. В подобных случаях требуется, чтобы _Singleton_ получал при необходимости новый экземпляр _Prototype_, а не хранил единственный и постоянный экземпляр _Prototype_. Example: link:https://www.baeldung.com/spring-inject-prototype-bean-into-singleton[baeldung]. +
BTW, we can also use *_@Scope(
value = ConfigurableBeanFactory.SCOPE_PROTOTYPE,
proxyMode = ScopedProxyMode.TARGET_CLASS)_* +
Пример *_@Scope_* с параметрами проиллюстрирован ниже: бин имеет скоуп реквест, и при внедрении этого бина в синглтон бин, синглтон по факту получает прокси, в который при каждом запросе сетается новый реальный бин скоупа реквест (also see link:https://www.baeldung.com/spring-bean-scopes#1-request-scope[baeldung]):

[source, java]
----
@Bean
@Scope(value = WebApplicationContext.SCOPE_REQUEST, proxyMode = ScopedProxyMode.TARGET_CLASS)
public HelloMessageGenerator requestScopedBean() {
    return new HelloMessageGenerator();
}
----

Рассмотрим случай, когда класс *_LockOpener_* предоставляет услуги для открытия любого шкафчика. С этой целью класс *_LockOpener_* полагается на внедренный в неm класс *_KeyHelper_*. Но структура класса *_KeyHelper_* предусматривает наличие ряда внутренних состояний, что делает этот класс непригодным для повторного использования. Всякий раз, когда вызывается метод *_openLock()_*, требуется новый экземпляр типа *_KeyHelper_*. В этом случае объект типа *_LockOpener_* - это _Singleton_. Но если внедрить класс *_KeyHelper_* с помощью обычного механизма, то повторно будет использоваться тот же самый его экземпляр, который был получен, когда каркас Spring внедрял данный класс в первый раз. Чтобы обеспечить передачу нового экземпляра класса *_KeyHelper_* методу *_openLock()_* при каждом его вызове, необходимо внедрить данный класс через метод поиска.

Как правило, этого можно добиться, реализовав в _Singleton_-классе интерфейс *_ApplicationContextAware_*, который рассматривается в следующей главе. После этого _Singleton_ сможет искать новый экземпляр _Prototype_ всякий раз, когда он потребуется, используя для этой цели экземпляр типа *_ApplicationContext_*. +
Внедрение же зависимостей через метод поиска позволяет объявить в _Singleton_, что ему требуется неодиночная зависимость и что он будет получать новый  _Prototype_ всякий раз, когда ему приходится взаимодействовать с ним, не прибегая к реализации любого характерного для Spring интерфейса.

*_See_* _p141_di_via_lookup_method/..._

----
specificLookupBean: Singer Instances the Same? false
1OOOOO gets took 179ms
standardLookupBean: Singer Instances the Same? true
1OOOOO gets took 0ms
----

Внедрение зависимостей через метод поиска предназначено для тех случаев, когда требуется работать с двумя Beans, имеющими *_разные жизненные циклы_*. Обычно это не нужно, если Beans имеют один и тот же жизненный цикл, особенно когда они оба _Singleton_. В результатах выполнения наглядно показаны заметные отличия в производительности между внедрением через метод поиска для получения новых экземпляров зависимости и стандартным внедрением для получения одиночного экземпляра зависимости.

Кроме того, внедрением зависимостей через метод поиска не следует пользоваться без особой нужды, даже если имеются компоненты Spring Beans с разными жизненными циклами. Допустим, имеются три _Singleton_, разделяющих общую зависимость. Каждый _Singleton_ должен иметь собственный экземпляр зависимости, поэтому зависимость создается как неодиночный объект, но требуется, чтобы каждый _Singleton_-Bean использовал один и тот же экземпляр взаимодействующего объекта на протяжении всего срока своего действия. В таком случае идеальным решением будет внедрение зависимостей через метод установки, а внедрение зависимостей через метод поиска лишь повлечет за собой нежелательные издержки.