=== Именование компонентов Spring Beans

В каркасе Spring поддерживается довольно сложная структура именования компонентов Spring Beans. Каждый компонент Spring Bean должен иметь по крайней мере одно однозначное имя в содержащем его контексте типа ApplicationContext.

Если в дескрипторе разметки _<bean>_ предусмотрен атрибут *_id_*, его значение служит в качестве имени Bean. Если атрибут *_id_* не указан, Spring ищет атрибут *_name_*, и если он определен, то используется *_первое имя_*, заданное в атрибуте name. (Именно первое имя, потому что в атрибуте name допускается определять целый ряд имен.) Если не указан ни атрибут *_id_*, ни атрибут *_name_*, то в качестве имени компонента в Spring выбирается *_имя его класса_*, разумеется, при условии, что оно не используется другими бинами. А если целый ряд компонентов Spring Beans без указанных атрибутов id и name имеет одно и то же имя класса, то Spring сгенерирует исключение *_NoSuchBeanDefinitionException_* при внедрении зависимостей во время инициализации контекста типа ApplicationContext.

*_See_* _p155_beans_naming/BeanNamingTest.java_, _p155_beans_naming/app-context-01.xml_

Компонентам Spring Beans разрешается иметь не одно, а несколько имен (через разделители) в атрибуте name. Можно также воспользоваться дескриптором разметки *_<alias>_*. Пример Bean с несколькими именами:

[source,xml]
----
<beans xmlns="...">
    <bean id="john" name="jon johnny,jonathan;jim"
        class="java.lang.String"/>
    <alias name="john" alias="ion"/>
</beans>
----

Как видите, для Bean назначено шесть имен. Первое имя указано в атрибуте *_id_*, еще четыре имени заданы в атрибуте *_name_* списком, в котором применяются все разрешенные разделители (это сделано только в целях демонстрации). Еще один псевдоним определен с помощью дескриптора *_<alias>_*.

==== Именование компонентов Spring Beans с помощью аннотаций в конфигурациях

*_See_* _pages 161-167_ (аннотации)
