=== Разрешение зависимостей

При нормальном функционировании каркас Spring способен разрешать зависимости, просматривая файл конфигурации или аннотации в классах. Но Spring ничего не известно о тех зависимостях между компонентами в коде, которые отсутствуют в конфигурации. И вполне возможно, что какой-нибудь компонент будет создан и настроен прежде своих зависимостей.

Допустим, что один бин _johnMayer_ типа *_Singer_* получает другой бин _gopher_ типа *_Guitar_* через вызов метода *_ctx.getBean()_* и затем использует его, причем бин типа *_Guitar_* получается через вызов *_ctx.getBean("gopher")_* *_без конфигурации_* _внедрения зависимостей_ (а-ля @Autowired над setter, field, etc). И в этом случае каркас Spring остается в неведении относительно того, что один его компонент _johnMayer_ зависит от другого его компонента _gopher_, и в конечном итоге он может создать бин *_johnMayer_* прежде бина *_gopher_*.

Эту проблему надо решать. Дополнительные сведения о зависимостях между Beans можно предоставить с помощью атрибута *_depends-on_* в дескрипторе разметки _<bean>_ (XML-config).

[source,xml]
----
<beans xmlns="...">
    <bean id="johnMayer" class="book.p172_dependencies_resolving.Singer"
        depends-on="gopher"/>
    <bean id="gopher" class="book.p172_dependencies_resolving.Guitar"/>
</beans>

----

В приведенной выше конфигурации утверждается, что bean _johnMayer_ зависит от bean _gopher_. Но для этого бину _johnMayer_ требуется доступ к контексту типа *_ApplicationContext_*. Следовательно, Spring должен внедрить эту ссылку, чтобы воспользоваться ею при вызове метода *_johnMayer.sing()_* для предоставления компонента _gopher_. С этой целью в классе *_Singer_* _реализуется интерфейс_ *_ApplicationContextAware_*, обеспечивающий в Spring реализацию *_метода установки_* специально для объекта типа ApplicationContext. Он _автоматически обнаруживается контейнером инверсии управления_ в Spring для внедрения контекста типа ApplicationContext, в котором создается компонент Spring Bean. +
Поскольку это делается *_после вызова конструктора_* компонента Spring Bean, то примененять контекст типа ApplicationContext в конструкторе компонента Spring Bean нельзя - это приведет к _NullPointerException_.

Разумеется, для конфигурации в формате XML имеется равнозначная аннотация. В классе Singer размещается аннотация @DependsOn, равнозначная атрибуту depends-on из конфигурации в формате XML.

*_See_* _p172_dependencies_resolving/Singer.java_

Аннотация используется для *_назначения зависимости_* между бинами. Гарантируется, что зависимые бины будут инициализированы *_после_* независимых. Необходимо упомянуть о важных моментах:

- While using @DependsOn, we *_must use component-scanning_*
- If a DependsOn-annotated class is declared via XML (_depends-on_), @DependsOn annotation metadata is *_ignored_*