=== Конфигурирование и начальная загрузка в Spring

В каркасе Spring предоставляется обширный ряд служб, дополняющих и расширяющих его основные возможности в отношении инверсии управления (IoC):

- *_Управление жизненным циклом компонентов Spring Beans._* Все представленные до сих пор компоненты Spring Beans были довольно просты и совершенно не привязаны к *_контейнеру инверсии управления_* в Spriпg. В этой части будут представлены стратегии, которые дают компонентам Spring Beans возможность *_получать уведомления из контейнера_* инверсии управления в Spring в разные моменты их жизненного цикла. Добиться этого можно: 1) реализовав *_специальные интерфейсы_*, предоставляемые в Spring 2) указав *_методы_*, которые Spring может вызывать через *_рефлексию_*, 3) или применив *_аннотации жизненного цикла_* компонентов JavaBeans, описанные в спецификации *_JSR-250_*.
- *_Информирование компонентов об их контексте в Spring_*. Иногда требуется, чтобы Bean имел возможность взаимодействовать со сконфигурировавшим его *_ApplicationContext_*. Для этих целей в Spring предоставляются два интерфейса, *_BeanNameAware_* и *_ApplicationContextAware_*, с помощью которых компонент Spring Bean может получить присвоенное ему имя и ссылку на контекст.
- *_Применение фабрик компонентов Spring Beans._* Интерфейс *_FactoryBean_* предназначен для реализации в любом Bean, который служит в качестве фабрики для других компонентов. В интерфейсе FactoryBean предоставляется механизм, позволяющий легко интегрировать собственные фабрики с помощью интерфейса *_BeanFactory_* из Spring.
- *_Работа с редакторами свойств компонентов JavaBeans._* Используется интерфейс *_java.beans.PropertyEditor_*. Редакторы свойств, реализующие *_PropertyEditor_*, служат для взаимного преобразования значений свойств и их строковых представлений типа *_String_*. Эти редакторы широко применяются в Spring, главным образом, для чтения значений, указанных в конфигурации по интерфейсу BeanFactory, а также для их приведения к нужному типу данных. В этой части обсуждается ряд редакторов свойств, предоставляемых в Spring, показывается, как пользоваться ими в приложениях, а также кратко поясняется, как самостоятельно реализовать специальные редакторы свойств.
- *_Подробное описание интерфейса ApplicationContext._* *_ApplicationContext_* расширяет интерфейс *_BeanFactory_*. В интерфейсе _ApplicationContext_ предоставляется полезный ряд дополнительных функциональных возможностей, включая 1) поддержку интернационализированных сообщений, 2) загрузку ресурсов и 3) публикацию событий. В этой части главы подробно рассматриваются его функциональные средства, дополняющие возможности инверсии управления. Забегая немного вперед, Также показано, каким образом интерфейс _ApplicationContext_ *_упрощает применение Spring_* при построении веб-приложений.
- *_Применение классов Java для конфигурирования._* До версии 3.0 каркас Spring поддерживал только базовую конфигурацию в формате XML с аннотациями для конфигурирования компонентов Spring Beans и зависимостей. Начиная со Spring 3.0 предлагается еще один способ *_конфигурирования интерфейса ApplicationContext с помощью классов Java_*.
- *_Применение модуля Spring Boot._* Конфигурирование приложений Spring можно сделать *_еще более практичным_* с помощью модуля Spring Boot. Этот модуль (и одноименный проект Spring) настолько упрощает создание автономных приложений промыШленного уровня на основе Spring, что их остается лишь запустить на выполнение.
- *_Применение функциональных средств, совершенствующих конфигурирование._* В этой части представлены функциональные средства, упрощающие конфигурирование приложений, в том числе *_управление профилями_*, *_абстракция среды и источников свойств_* и т.д. Здесь показывается, как применять эти функциональные средства для удовлетворения конкретных потребностей в конфигурировании.
- *_Применение языка Groovy для конфигурирования._* В версии *_Spring 4.0_* появилась новая возможность для конфигурирования определений компонентов Spring Beans на языке *_Groovy_*, который можно применять в качестве *_альтернативы или дополнения_* существующих способов конфигурирования средствами XML и Java.
