=== Редакторы свойств компонентов Spring Bean

(Из принципов JavaBeaлs) *_PropertyEditor_* - это интерфейс для взаимного преобразования типов внутреннего представления значений свойств и строк. Первоначально такое преобразование задумывалось как способ ввода значений свойств в виде строковых значений типа _String_ в редактор и последующего их преобразования в нужный тип.

В основном, свойства задается в файле конфигурации no интерфейсу BeanFactory и являются символьными строками. Тем не менее свойства, для которых указываются эти значения, могут и не относиться к типу String. Таким образом, вместо искусственного создания целого ряда свойств типа String в каркасе Spring можно *_определить редакторы свойств_*, чтобы управлять процессом *_конвертации_* свойств типа _String_ в нужные их типы.

Все редакторы свойств, входящие в состав либы _org.springframework.spring-beans_, можно увидеть в  в каталоге *_org.springframework.beans.propertyeditors_*. Они расширяют класс *_java.beans.PropertyEditorSupport_* и могут быть использованы для неявного преобразования строковых литералов типа _String_ в значения свойств, внедряемых в Beans. Это означает, что они предварительно зарегистрированы средствами интерфейса *_BeanFactory_*.

*_See_* _p239_property_editors/PropertyEditorBean.java_, _spring/p239_Property_editors/app-property-context.xml_

==== Кастомный редактор свойств

Иногда приходится создавать собственный редактор свойств для поддержки одного класса или целого ряда классов в приложении. В каркасе Spring обеспечивается полная поддержка регистрации специальных редакторов свойств через класс *_PropertyEditorSupport_*, который можно расширить в специальных редакторах свойств, реализовав один только метод *_setAsText()_*:

[source, java]
----
public class NamePropertyEditor exteпds PropertyEditorSupport {
  @Override
  public void setAsText(Striпg text) throws IllegalArguтeпtExceptioп {
    Striпg[] name = text.split("\\s");
    setValue(пew FullName(name[0], name[1]));
  }
}
----
