=== Применение Hibernate в Spring

Рассмотрим одну из библиотек
объектно-реляционного преобразования (ORM) под названием *_Hibernate_*. Среди всех open-source библиотек ORM она является одной из самых удачных.

*_See:_* Шпаргалка Java программиста 1: JPA и Hibernate в вопросах и ответах: link:https://habr.com/ru/post/265061/[]

Распространенность Hiberпate повлияла также на разработку спецификации объектов данных Java (Java Data Object - JDO) в качестве одной из стандартных технологий ORM на платформе Java ЕЕ. В версии EJB 3.0 компонент сущности EJB был даже заменен прикладным интерфейсом *_Java Persisteпce АРI (JPA_*), на многие принципы организации которого оказали влияние такие распространенные библиотеки ORM, как _Hibernate_, _TopLink_ и _JDO_.

Начиная с Hibernate 3.2 предоставляется реализация прикладного интерфейса *_JPA_*. Это означает, что при разработке приложений с помощью библиотеки Hibernate в качестве поставщика услуг сохраняемости данных можно выбирать между собственным прикладным интерфейсом _API библиотеки Hibernate_ и прикладным _JPA АРI с поддержкой Hibernate_.

Рассмотрим применение Hibernate в Spring. Hibernate является настолько обширной библиотекой ORM, что раскрыть все ее особенности (в данной книге) просто невозможно. Этой теме посвящены целые книги. Поэтому здесь рассматриваются основные принципы и примеры применения библиотеки Hibernate в Spring:

- *_Конфигурирование фабрики сеансов Hibernate_*. Основной принцип действия библиотеки Hibernate опирается на интерфейс *_Session_*, которым управляет компонент *_SessionFactory_*, представляющий фабрику сеансов в Hibernate. В этой части будет показано, как конфигурировать фабрику сеансов Hibernate для работы в приложении Spring.
- *_Основные принципы объектно-реляционного преобразования средствами Hibernate_*. В этой части рассмотрены основные принципы преобразования простых объектов POJO в структуру исходной реляционной базы данных с помощью библиотеки Hibernate. Здесь будут также описаны некоторые из наиболее употребительных отношений, в том числе _"один ко многим"_ и _"многие ко многим"_.
- *_Операции над данными_*. В этой части представлены примеры выполнения операций над данными (запроса, вставки, обновления, удаления) с помощью библиотеки Hibernate в среде Spring. В работе с библиотекой Hibernate взаимодействовать придется главным образом с ее основным интерфейсом Session.

==== Конфигурирование фабрики сеансов Hibernate

В каркасе Spring предоставляются классы, поддерживающие конфигурирование фабрики сеансов Hibernate в виде компонента Spring Bean с требующимися свойствами. Чтобы воспользоваться библиотекой Hibernate, необходимо внедрить ее как зависимость в свой проект.

Ниже перечислены основные элементы конфигурации Hibernate (*_See_* _p490_start_with_hibernate.config/AppConfig.java_ ):

- Компонент *_dataSource_*
- Компонент *_transactionManager_*. Для _транзакционного доступа_ к данным в фабрике сеансов Hibernate требуется диспетчер транзакций. В каркасе Spring предоставляется диспетчер транзакций специально для версии Hibernate 5 (_org.springframework.orm.hibernateS.HibernateTransactionManager_). Этот компонент объявлен с присвоенным ему идентификатором *_transactionManager_*. Всякий раз, когда потребуется диспетчер транзакций, Spring будет по умолчанию искать в контексте бин transactionManager (_про транзакции см главу 9_). Кроме того, аннотацией *_@EnableTransactionManagement_* объявляется поддержка требований к установлению границ транзакций.
- Компонент *_sessionFactory_*. Этот Bean является самой важной частью конфигурации, поскольку в нем определено немало свойств:
1. Во-первых, необходимо внедрить компонент *_dataSource_* в фабрику сеансов.
2. Во-вторых, библиотеке Hibernate предписывается просмотреть entities в пакете через метод *_setPackagesToScan()_*.
3. И, в-третьих, свойство *_hibernateProperties_* предоставляет подробности конфигурирования _Hibernate_. Наиболее важные конфигурационные параметры и соответствующие свойства для фабрики сеансов Hibernate представлены в таблице:



[cols="1,8"]
|===

|hibernate.dialect
|В библиотеке Hibernate поддерживаются диалекты SQL для многих баз данных. Эти диалекты являются подклассами, производными от класса _org.hibernate.dialect.Dialect_. *_E. G._* H2Dialect, Oracle10gDialect, PostgreSQLDialect, МySQLDialect, SQLServerDialect.

|hibernate.max_fetch_depth
|Объявляет "глубину" для внешних соединений, когда одни преобразующие объекты связаны с другими преобразуемыми объектами. Позволяет предотвратить выборку средствами Hibernate слишком большого объема данных при наличии многих вложенных ассоциаций. _Def value_ = *_З_*

|hibernate.jdbc.fetch_size
|While executing sql query using JDBC by _default_, JDBC ResultSet fetching size is *_10_* records for each fetch. It leads to performance issue when reading big amount of data (>50). In that case, We can set *_fetch_size_* like 100, 1k, 10k, 20k etc to increase the performance. _Def value_ = *_10_*

|hibernate.jdbc.batch_size
|Количество операций обновления, которые группируются в *_пакет_*. Это позволяет обновлять большое количество данных пакетами. Например, если вы создаете 100 записей и *_batch_size=50_*, то вместо того, чтобы вызвать INSERT SQL 100 раз, Hibernate сгруппирует их в пакеты по 50 и вызовет INSERT 2 раза. _Def value_ = *_0_* (no batch used)

|hibernate.show_sql
|Указывает Hibernate направлять запросы SQL в файл регистрации или на консоль. Используется для dev-целей. [false/true]

|hibernate.format_sql
|Указывает, следует ли форматировать вывод запросов SQL на консоль или в файл регистрации. [false/true]

|hibernate.use_sql_comments
|Hibernate формирует комментарии в запросах SQL, чтобы упростить их отладку. [false/true]

|===

==== max_fetch_depth - что это?

Imagine a Person and an Address Entity. Each person lives at one address (very simple system), but many people might live at the same address. In the object model a Person would probably have an address property. This would be mapped as many-to-one (as the doc says). Now when fetching a Person from the database, hibernate encounters this property. In the database it's a column with a foreign key to the Address table. To fetch the associated object, a join to this table can be used. The resulting data would be used to populate an Address object that would be set on the address property on the person. In this sense Hibernate traverses the object graph when fetching an object. +
Now what if Address had a property City? This would also be many-to-one and would lead to a join by the same logic. What if City had a property Country? Same thing. Doing many joins would be bad for performance. At some point it would be better to do a separate select, get the data from a cache or inject a proxy. This configuration property determines how many associations hibernate will traverse by join when fetching data.
