=== Java Persistence API - JPA

Библиотека _Hibernate_ и эффективный язык запросов *_HQL_* добились немалых успехов в преобразовании простых объектов POJO, а также повлияли на разработку стандартов, определяющих технологии доступа к данным в области Java. После Hiberпate в организации *_JCP_* был подготовлен стандарт *_JDO_* (_Java Data Objects_), а затем и прикладной *_интерфейс JPA_*.

*_See:_* Шпаргалка Java программиста 1: JPA и Hibernate в вопросах и ответах: link:https://habr.com/ru/post/265061/[]

На момент 2019 года JPA достиг версии _2.1_ и поддерживает такие стандартизованные понятия, как

- контекст сохраняемости (аннотация *_@PersistenceContext_*)
- диспетчер сущностей (интерфейс *_EntityManager_*)
- и язык *_JPQL_* (Java Persisteпce Query Language - язык запросов сохраняемости в Java).

Такая стандартизация предоставляет разработчикам возможность менять поставщиков услуг сохраняемости JPA, таких как _Hibernate_, _EclipseLink_, _Oracle TopLiпk_ и _Apache OpenJPA_. В каркасе Spring также предоставляется отличная поддержка прикладного интерфейса JPA. Например, для начальной загрузки диспетчера сущностей JPA имеется несколько реализаций компонента Spring Bean типа *_EntityManagerFactory_* с поддержкой всех упомянутых ранее поставщиков услуг JPA. +
В рамках проекта *_Spring Data_* ведется также подпроект *_Spring Data JPA_*, ориентированный на расширенную поддержку применения JPA в приложениях Spring. К числу основных возможностей проекта Spring Data JPA относятся понятия *_хранилища_* и *_спецификации_*, а также поддержка предметно-ориентированного языка запросов *_QueryDSL_* (Query Domain Specific Language).

Example of QueryDSL:
[source, java, test]
----
QUser user = QUser.user;

User c = queryFactory.selectFrom(user)
  .where(user.login.eq("David"))
  .fetchOne();
----

Далее будут рассмотрены следующие вопросы:

1. *_Основные понятия JPA_*. В этой части поясняется ряд основных понятий прикладного интерфейса JPA.
2. *_Конфигурирование диспетчера сущностей JPA_*. В этой части обсуждаются реализации компонента типа *_EntityManagerFactory_*, поддерживаемые в Spring, а также способы конфигурирования наиболее употребительной из них - класса *_LocalContainerEntityManagerFactoryBean_* - при конфигурировании Spring в формате XML.
3. *_Операции с данными_*. В этой части показано, как в JPA реализуются элементарные операции над базой данных, которые в принципе мало чем отличаются от аналогичных операций, реализуемых с помощью Hibernate.
4. *_Расширенные операции обработки запросов_*. В этой части рассмотрено применение собственных запросов в JPA, а также строго типизированный прикладной интерфейс АРI критериев поиска для реализации более гибких операций обработки запросов в JPA.
5. *_Введение в Spring Data JPA_*. В этой части описан проект Spring Data JPA и пояснено, каким образом он позволяет упростить разработку логики доступа к данным.
6. *_Отслеживание изменений в сущностях и аудит_*. Общим требованием коперациям обновления базы данных является отслеживание дат создания и обновления сущностей, а также того, кто производил их изменение. Кроме того, требуется такая критически важная информация, как сведения о клиенте и данные из таблицы предыстории, где обычно хранятся все версии сущности. Здесь будет показано, каким образом Spring Data JPA и Hibernate Envers (Hibernate Entity Versioning System - система контроля версий сущностей Hibernate) могут упростить разработку подобного рода логики.
