=== Структура и конфигурация JPA

- Структура
- Конфигурирование бина *_EntityManagerFactory_* из интерфейса JРА

==== Структура

В основу JPA положен интерфейс *_EntityManager_*, который происходит от фабрик типа *_EntityManagerFactory_*. Главное назначение интерфейса _EntityManager_ - поддержка *_контекста сохраняемости_*, в котором будут храниться все экземпляры сущностей, управляемые этим контекстом. +
*_Конфигурация_* интерфейса EntityManager определяется как *_единица сохраняемости_*, и в приложении может существовать *_не одна_* такая единица. Если применяется библиотека Hibernate, то _контекст сохраняемости_ эквивалентен интерфейсу *_Session_*, а компонент _EntityManagerFactory_ - компоненту *_Session Factory_*.

В библиотеке Hibernate управляемые сущности сохраняются в сеансе, с которым можно взаимодействовать напрямую через компонент _SessionFactory_ или интерфейс _Session_. Но в JPA *_нельзя непосредственно взаимодействовать с контекстом сохраняемости_*. Вместо этого приходится полагаться на интерфейс *_EntityManager_*.

Языки *_JPQL_* и *_HQL_* очень похожи, но в JPA 2 появился строго типизированный прикладной интерфейс *_API Criteria_* для критериев поиска, который полагается на метаданные преобразуемых сущностей при составлении запроса. _API Criteria_ более эффективен, т. к. в нем любые ошибки будут обнаруживаться во время компиляции, а не во время выполнения.

==== Конфигурирование бина EntityManagerFactory из интерфейса JРА

Для применения JPA в Spring необходимо сконфигурировать компонент типа *_EntityManagerFactory_*, как это делалось ранее для компонента типа _SessionFactory_ в _Hibernate_. В каркасе Spring поддерживаются три способа конфигурирования компонента типа _EntityManagerFactory_, но третий используется наиболее часто. В этом случае используется бин *_LocalContainerEntityManagerFactoryBean_* и поддерживается внедрение источника данных и допускается участие как в _локальных_, так и в _глобальных транзакциях_.

*_See_* _p538_JPA_configuration_n_structure/config/JpaConfig.java_

В конфигурации _JpaConfig.java_ объявлено несколько бинов для поддержки конфигурации класса _LocalContainerEntityManagerFactoryBean_ вместе с библиотекой _Hibernate_ в качестве поставщика услуг сохраняемости. Рассмотрим основные компоненты такой конфигурации:

- Компонент *_dataSource_*.
- Компонент *_transactionМanaqer_*. Компоненту типа *_EntityManagerFactory_* требуется _диспетчер транзакций_ для транзакционного доступа к данным. В каркасе Spring предоставляется диспетчер транзакций (_org.springframework.orm.jpa.JpaTransactionManager_) специально для JPA. Этот бин объявляется с идентификатором transactionManager. Более подробно транзакции рассматриваются в главе 9. А аннотация @EnableTransactionManagement используется 'to enable transactional support' в @Configuration классе.
- Компонент *_EntityManagerFactory_* интерфейса JPA. Компонент *_emf_* является _наиболее важным_ в данной конфигурации. +
Прежде всего, он объявляется для применения класса _LocalContainerEntityManagerFactoryBean_. В этом компоненте предоставляются различные свойства.
1. Во-первых, как и следовало ожидать, необходимо внедрить компонент типа DataSource.
2. Во-вторых, в свойстве _jpaVendorAdapter_ указывается класс *_HibernateJpaVendorAdapter_*, поскольку применяется библиотека Hibernate.
3. В-третьих, фабрике сущностей предписывается просмотреть обьекты предметной области с аннотациями преобразований ORM в определенных пакетах через *_setPackagesToScan()_*. Такая возможность доступна только с версии Spring 3.1, и благодаря поддержке просмотра классов предметной области можно опустить определение _единицы сохраняемости_ в файле *_META-INF/persistence.xml_*.
4. И, наконец, в свойстве *_jpaProperties_* задаются подробности конфигурации для поставщика услуг сохраняемости из библиотеки Hibernate.