== JPA аннотации и запросы

- JPA аннотации [p 546]
- Запрашивание данных на языке JPQL [p 546]
- Вставка данных [p 563]
- Обновление данных [p 566]
- Удаление данных [p 567]
- Native queries, @SqlResultSetMapping, запрос non-entity классов [p 569]
- Criteria API (JРА 2) для запросов с критериями поиска [p 572]


=== JPA аннотации

Код, написанный ранее для _Hibernate_, ксодержит совместимые с JPA аннотации пакета _javax.persistence_, а это означает, что они уже совместимы с _JPA_.

Как только компонент типа _EntityManagerFactory_ будет сконфигурирован надлежащим образом, внедрить его в свои классы не составит большого труда. Ниже приведен исходный код класса SingerServiceimpl, который послужит в качестве примера для выполнения операций в базе данных через прикладной интерфейс JPA.

*_See_* _p538_JPA_configuration_n_structure/service/SingerServiceImpl.java_

В _SingerServiceImpl.java_ применяется несколько аннотаций:

- *_@Service_* - по сути, ничем не отличается от *_@Component_*. Разве что им маркируют сервисы.
- Аннотация *_@Repository_* указывает на то, что в данном классе содержится логика доступа к данным, а каркасу Spring предписывается _преобразовывать_ характерные для поставщика услуг _исключения_ в иерархию исключений типа *_DataAccessException_*, определенную в Spring.

Для внедрения интерфейса *_EntityManager_* служит аннотация *_@PersistenceContext_*, которая является стандартной аннотацией JPA для внедрения диспетчера сущностей. На вопрос, почему выбрано такое имя, можно ответить, что сам контекст сохраняемости (persistence) находится под управлением интерфейса *_EntityManager_*. Если в приложении присутствует немало единиц сохраняемости, в аннотацию можно также ввести атрибут *_unitName_*, чтобы указать внедряемую единицу сохраняемости. Обычно единица сохраняемости представляет отдельный источник данных типа DataSource в СУРБД.

=== Запрашивание данных на языке JPQL

*_See_* _p538_JPA_configuration_n_structure/service/SingerServiceImpl.java_

В методе _SingerServiceImpl.findAll()_ вызывается метод *_EntityManager.createNamedQuery()_*, которому передается имя запроса и ожидаемый тип возвращаемого результата. В данном случае _диспетчер сущностей_ типа *_EntityManager_* возвратит реализацию интерфейса _TypedQuery<X>_. Затем вызывается метод _TypedQuery.getResultList()_ для извлечения сведений о певцах. +

А метод _SingerServiceImpl.listSingersWithAlbumAndInstrument()_ будет выбирать все связанные альбомы и музыкальные инструменты. В нем используется другой именованный запрос с активизированным предложением *_left join fetch_*.

Также представлена возможность найти Singer по его id в методе _SingerServiceImpl.findById()_

Пример работы с этими методами можно увидеть в: +
*_See_* _SpringJPADemo.call_listAll(...)_, _SpringJPADemo.call_listSingersWAnI(...)_, _SingerServiceImpl.call_findById(...)_

=== Вставка данных

Вставка данных средствами JPA осуществляется очень просто. Как и в библиотеке Hibernate, в прикладном интерфейсе JPA поддерживается извлечение первичного ключа, генерируемого базой данных.

*_See_* _SingerServiceImpl.findById()_, _QueryHelper.insert()_

Если id = null, значит, это новый экземпляр сущности и будет вызван метод *_EntityManager.persist()_*. При вызове _persist()_ _диспетчер сущностей_ *_EntityManager_* сохраняет сущность и делает ее управляемым экземпляром в контексте сохраняемости. +
Если же значение id существует, значит, выполняется обновление и будет вызван метод *_EntityManager.merge()_*.

ВАЖНО! (*_See_* _QueryHelper.insert()_) После добавления зависимого объекта в список главного (*_one-to-many_*), надо *_установить главный объект в соответствующее поле зависимого объекта_*. В противном случае зависимый объект (_Album_) не сможет сохраниться и упадет с *_"singer_id is null"_*. Пример такого кода представлен ниже:

[source, java]
----
singer.getAlbums().add(album1);
album1.setSinger(singer);
----

=== Обновление данных

Допустим, для певца необходимо обновить имя и удалить альбом. _Удаление альбома возможно потому_, что в связи *_@OneToMany_* определен атрибут *_orphanRemoval=true_*, предписывающий поставщику услуг JPA (Hibernate) удалить все висячие записи, существующие в базе данных, но больше не обнаруживаемые в объекте при сохранении.

Удаление альбома через удаление из сета фиг настроишь. Зато можно вызвать "clear()" и зачистить все. +
А вот имя изменяется.

*_See_* _SingerServiceImpl.findById()_, _QueryHelper.update(...)_

=== Удаление данных

Прежде всего, необходимо вызвать метод *_EntityManager.merge()_* для объединения состояния сущности с текущим контекстом сохраняемости. Затем вызывается метод *_EntityManager.remove()_*, которому передается смерженный экземпляр. Метод _remove()_ удаляет запись о певце, а также все связанные с ним альбомы, поскольку в преобразовании было задано условие *_cascade=CascadeType.ALL_*. Для инструментов каскадность не настроена - что логично, там тип связи *_@ManyToMany_*.

*_See_* _SingerServiceImpl.delete()_, _QueryHelper.delete(...)_

=== Native queries, @SqlResultSetMapping, запрос non-entity классов

В JPA поддерживается выполнение собственных запросов. _EntityManager_ отправит такой запрос базе данных в исходном виде, не производя никакого преобразования или видоизменений. Пример: +
*_See_* _QueryHelper.checkNativeQuery()_, _SingerServiceImpl.findSingersByNativeQuery()_

Главное преимущество, которое дает применение собственных запросов в JPA, заключается в преобразовании результирующего набора типа _ResulSet_ в классы сущностностей, преобразованных по принципу ORM. Кроме преобразованного объекта предметной области, можно передавать строку, обозначающую наименование преобразования результирующего набора SQL. Преобразование результирующего набора SQL определяется на уровне класса сущности с помощью аннотации *_@SqlResultSetMapping_*, как показано ниже. В свою очередь, преобразование результирующего набора SQL может состоять из одного или более преобразования сущностей и столбцов.

"Грубая настройка" столбцов в *_@SqlResultSetMapping()_* приведет к тому, что мы будем получать массив объектов *_Object[]_*. Пример такого _@SqlResultSetMapping_ - *_"singerResult2"_* +
*_See_* _SingerServiceImpl.findObjectsByNativeQuery()_

Но *_@SqlResultSetMapping()_* может быть *_очень полезен_*, если мы хотим, например:

1. Выбрать для преобразования *_не все столбцы_* некоторой entity, а а часть из них.
2. Получить результат в виде *_не entity класса_*

Примером такого non-entity класса является _ReducedSinger.java_, который, к тому же, еще и _не serializable_. Производится выборка ограниченного количества столбцов (_REDUCED_SINGER_NATIVE_QUERY_), после чего применяется _@SqlResultSetMapping_ - *_"singerResult3"_*. Данный setMapping имеет под собой анноташку *_@ConstructorResult_*, которая раскладывает значения из квери в конструктор _ReducedSinger.java_. +
*_See_* _SingerServiceImpl.findReducesSingersByNativeQuery()_ +

Важное замечание: мы не можем *_напрямую_* выполнить преобразование к _ReducedSinger.java_ через _ReducedSinger.class_:
[source, java]
----
  public List<ReducedSinger> findReducesSingersByNativeQuery() {
    return em.createNativeQuery(REDUCED_SINGER_NATIVE_QUERY,
        ReducedSinger.class).getResultList();
  }
----
Поскольку в этом случае мы получим исключение *_org.hibernate.MappingException: Unknown entity: ReducedSinger_*. Именно поэтому мы и используем *_@SqlResultSetMapping_*.

=== Criteria API (JРА 2) для запросов с критериями поиска

JPA поддерживает *_Criteria API_* для составления запросов с критериями поиска. В JPA 2 даже можно использовать автогенерируемые метамодели entity-классов (p572, book). Однако здесь мы рассмотрим стандартное применение _Criteria API_

*_See_* _SingerServiceImpl.findByCriteriaQuery(String firstName, String lastName)_

По ссылке link:https://www.baeldung.com/spring-data-criteria-queries[baeldung] также рассматривается  имплементирование _@Repository_ интерфейса _JpaSpecificationExecutor_, чтобы не писать boilerplate-код и др.