=== JPA аннотации и запросы

==== JPA аннотации

Код, написанный ранее для _Hibernate_, ксодержит совместимые с JPA аннотации пакета _javax.persistence_, а это означает, что они уже совместимы с _JPA_.

Как только компонент типа _EntityManagerFactory_ будет сконфигурирован надлежащим образом, внедрить его в свои классы не составит большого труда. Ниже приведен исходный код класса SingerServiceimpl, который послужит в качестве примера для выполнения операций в базе данных через прикладной интерфейс JPA.

*_See_* _p538_JPA_configuration_n_structure/service/SingerServiceImpl.java_

В _SingerServiceImpl.java_ применяется несколько аннотаций:

- *_@Service_* - по сути, ничем не отличается от *_@Component_*. Разве что им маркируют сервисы.
- Аннотация *_@Repository_* указывает на то, что в данном классе содержится логика доступа к данным, а каркасу Spring предписывается _преобразовывать_ характерные для поставщика услуг _исключения_ в иерархию исключений типа *_DataAccessException_*, определенную в Spring.

Для внедрения интерфейса *_EntityManager_* служит аннотация *_@PersistenceContext_*, которая является стандартной аннотацией JPA для внедрения диспетчера сущностей. На вопрос, почему выбрано такое имя, можно ответить, что сам контекст сохраняемости (persistence) находится под управлением интерфейса *_EntityManager_*. Если в приложении присутствует немало единиц сохраняемости, в аннотацию можно также ввести атрибут *_unitName_*, чтобы указать внедряемую единицу сохраняемости. Обычно единица сохраняемости представляет отдельный источник данных типа DataSource в СУРБД.

==== Запрашивание данных на языке JPQL

*_See_* _p538_JPA_configuration_n_structure/service/SingerServiceImpl.java_

В методе _SingerServiceImpl.findAll()_ вызывается метод *_EntityManager.createNamedQuery()_*, которому передается имя запроса и ожидаемый тип возвращаемого результата. В данном случае _диспетчер сущностей_ типа *_EntityManager_* возвратит реализацию интерфейса _TypedQuery<X>_. Затем вызывается метод _TypedQuery.getResultList()_ для извлечения сведений о певцах. +

А метод _SingerServiceImpl.listSingersWithAlbumAndInstrument()_ будет выбирать все связанные альбомы и музыкальные инструменты. В нем используется другой именованный запрос с активизированным предложением *_left join fetch_*.

Пример работы с этими методами можно увидеть в: +
*_See_* _SpringJPADemo.call_listAll(...)_, _SpringJPADemo.call_listSingersWAnI(...)_