== Транзакции

См. также link:https://medium.com/@kirill.sereda/%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%B2-spring-framework-a7ec509df6d2[tutorial (rus)] и link:https://www.javainuse.com/spring/transaction-interview[transaction-interview questions] +
А также link:https://www.javainuse.com/spring/springtrans[Spring Boot Transaction Management Tutorial]

Транзакции - одна из самых важных составляющих построения надежного корпоративного приложения . Наиболее распространенным типом транзакции является *_операция в базе данных_*. В ходе типичной операции обновления начинается транзакция в базе данных, где данные обновляются, а по результатам выполнения этой операции в базе данных транзакция фиксируется или откатывается. Но зачастую, в зависимости от требований к приложению (СУРБД, ERP), управление транзакциями может оказаться более сложным.

На 3аре разработки приложений на Java (после появления JDBC, но до того, как стал доступным стандарт JEE или каркас Spring) разработчики управляли транзакциями в прикладном коде. А когда появился стандарт JEE, точнее - стандарт EJB, разработчики получили возможность пользоваться управляемыми контейнером транзакциями (СМТ), чтобы управлять ими декларативно. Но сложное объявление транзакций в дескрипторе развертывания EJB все же было трудно поддерживать, а кроме того, оно излишне усложняло обработку транзакций. Некоторые разработчики предпочитали иметь больший контроль над транзакциями и поэтому - выбирали управляемые компонентами транзакции (ВМТ), чтобы управлять ими программно. Тем не менее программирование с помощью JТА (Java Transaction API - прикладной интерфейс Java для транзакций) было достаточно сложным.

В этой главе будет показано, каким образом каркас Spring может упростить _реализацию логики обработки транзакций_. В каркасе Spring предоставляется поддержка как *_декларативного_*, так и *_программного_* способа управления транзакциями.

В случае использования _декларативных_ транзакций Spring бизнес-логика не загромождается кодом управления транзакциями. Все, что требуется сделать, - это объявить методы (в классах или на соответствующих уровнях абстракции), которые должны принимать участие в транзакции, вместе с подробностями конфигурации транзакций, а каркас Spring сам позаботится о поддержке управления транзакциями. В этой главе будут, в частности, рассмотрены следующие темы:

- *_Уровень абстракции транзакций в Spring_*. В этой части описаны основные составляющие классов транзакций в Spring, а также пояснено, как применять эти классы для управления свойствами транзакций.
- *_Декларативное управление транзакциями_*. В этой части показано, как пользоваться каркасом Spring и простыми объектами Java для реализации декларативного управления транзакциями.
- *_Программное управление транзакциями_*. Несмотря на то что программное управление транзакциями _применяется очень редко_, в этой части поясняется, как пользоваться предоставляемым в Spring классом *_TransactionTemplate_*, обеспечивающим полный контроль над кодом управления транзакциями.
- *_Глобальные транзакции через прикладной интерфейс JTA_*. Что касается глобальных транзакций, которые должны охватывать _несколько ресурсов сервера базы данных_, то в этой части будет показано, как конфигурировать и реализовать глобальные транзакции в Spring, используя прикладной интерфейс JTA.