== Isolation levels в БД


=== MySQL vs Postgres

- *Repeatable Read* - дефолтный isolation level в MySQL
- *Read Committed* - дефолтный isolation level в PostgreSQL

=== Ошибки чтения в БД

Что такое Dirty write, Dirty read, Lost update, Phantom read, Read skew и пр +
Смотри по ссылке link:https://habr.com/ru/company/otus/blog/501294/[habr]


=== Основные 4 уровня изоляции

- READ UNCOMMITTED — это наименее строгий уровень изоляции, так как он игнорирует блокировки, размещенные другими транзакциями. Транзакции, выполняемые с помощью инструкции READ UNCOMMITTED, могут считывать измененные значения данных, которые еще не были зафиксированы другими транзакциями. Такие операции чтения называются чтением "грязных" данных.

- READ COMMITTED предотвращает операции чтения "грязных" данных, указывая, что инструкции не могут считывать значения данных, которые были изменены, но еще не зафиксированы другими транзакциями. Другие транзакции по-прежнему могут изменять, вставлять или удалять данные между выполнениями отдельных инструкций в текущей транзакции, результатом чего будет неповторяемое чтение или фантомные данные.

- SNAPSHOT (это дополнительный уровень) указывает, что данные, считываемые в рамках транзакции, никогда не будут отражать изменения, внесенные другими одновременными транзакциями. Транзакция использует версии строк данных, которые существуют в начале транзакции. При чтении данные не блокируются, поэтому транзакции моментальных снимков не блокируют запись данных другими транзакциями. Транзакции, осуществляющие запись данных, не блокируют считывание данных транзакциями моментальных снимков. Для использования изоляции моментальных снимков необходимо включить ее, настроив параметр базы данных ALLOW_SNAPSHOT_ISOLATION.

- REPEATABLE READ — это более строгий уровень изоляции, чем READ COMMITTED и SNAPSHOT. Он включает в себя READ COMMITTED и дополнительно указывает, что никакие другие транзакции не могут изменять или удалять данные, которые были считаны текущей транзакцией, пока текущая транзакция не будет зафиксирована. Cовмещаемые блокировки на считываемых данных сохраняются до завершения транзакции и не снимаются в конце каждой инструкции.

- SERIALIZABLE — самый строгий уровень изоляции, поскольку он блокирует целые диапазоны ключей и сохраняет блокировку до завершения транзакции. Он включает в себя REPEATABLE READ и добавляет ограничение, запрещающее другим транзакциям вставлять новые строки в диапазоны, которые были прочитаны транзакцией, пока транзакция не будет завершена.

===== Repeatable read/Read Committed - what is it?

(не очень уверен в качестве этого куска, можно см link:https://habr.com/ru/post/317884/[habr])

*_Repeatable read_* обеспечивает согласованное чтение в рамках одной и той же транзакции, а это означает, что при первом чтении будет создан _моментальный снимок_ (момент времени), а все последующие чтения будут согласованными по отношению друг к другу. Конечно, хранение таких снимков имеет свои последствия, но гарантирует хороший уровень согласованности. +
*_Read Committed_* — запрос SELECT (без предложения FOR UPDATE/SHARE) видит только данные, зафиксированные до начала запроса; он никогда не видит ни незафиксированные данные, ни изменения, зафиксированные во время выполнения запроса параллельными транзакциями. По сути, запрос SELECT видит моментальный снимок базы данных на момент начала выполнения запроса. Однако SELECT видит результаты предыдущих обновлений, выполненных в рамках его собственной транзакции, даже если они еще не зафиксированы. Также обратите внимание, что две последовательные команды SELECT могут видеть разные данные, даже если они находятся в одной транзакции, если другие транзакции фиксируют изменения после запуска первой команды SELECT и до начала второй команды SELECT.

=== UNSORTED

Есть три различных аномалии согласованности, которые аналогичны феномену чтения:

Грязное чтение — происходит, когда транзакция читает незафиксированные данные. Другими словами, транзакции разрешено читать данные, которые были изменены другими транзакциями и еще не зафиксированы.

Неповторяющееся чтение — происходит, когда в одной и той же транзакции мы извлекаем одну и ту же строку более одного раза, но значения для этой строки могут быть разными. Это происходит потому, что после того, как первая транзакция считывает данные в строке, другим транзакциям разрешается изменять эти данные.

Фантомные чтения — возникают, когда в одной и той же транзакции одинаковые запросы возвращают разные строки. Причина такого поведения заключается в том, что между первым и вторым выполнением запроса в таблицу были вставлены новые строки другими транзакциями, которые соответствуют критериям выбора.

Как упоминалось выше, уровень изоляции Repeatable Read SQL Server предотвращает грязные чтения и неповторяемые чтения. Это достигается размещением общих блокировок на все данные, которые считываются каждым оператором в транзакции, и все блокировки удерживаются до завершения транзакции. В результате другие транзакции не могут изменить данные, которые были прочитаны текущей транзакцией. Однако это не мешает другим транзакциям вставлять новые строки в таблицы, которые были выбраны в текущей транзакции, более того, эти новые строки могут соответствовать условиям выбора в операторах текущей транзакции. Таким образом, если эти операторы выполняются в текущей транзакции более одного раза и упомянутые новые строки вставляются между выполнениями этих операторов, происходят фантомные чтения.

Уровень изоляции Serializable SQL Server защищает от всех трех аномалий согласованности, и это достигается путем размещения блокировок диапазона в диапазоне значений ключа, соответствующих условиям поиска для всех инструкций в транзакции. Эти блокировки удерживаются до завершения транзакции. Это гарантирует, что не только предотвращены грязные и неповторяемые чтения, но и исключены фантомные чтения. Serializable — самый строгий уровень изоляции, но параллелизм ниже, чем на других уровнях изоляции транзакций.

==== SNAPSHOT ISOLATION

(all from link:https://www.sqlshack.com/snapshot-isolation-in-sql-server/[sqlshack])

Изоляция моментальных снимков позволяет избежать большинства блокировок и блокировок с помощью управления версиями строк. При изменении данных зафиксированные версии затронутых строк копируются в базу данных tempdb и получают номера версий. Эта операция называется копированием при записи и используется для всех вставок, обновлений и удалений с использованием этой техники. Когда другой сеанс считывает те же данные, возвращается зафиксированная версия данных на момент начала транзакции чтения.

Избегая большинства блокировок, этот подход может значительно увеличить параллелизм при меньших затратах, чем изоляция транзакций. Конечно, «Бесплатных обедов не бывает!» а изоляция моментальных снимков имеет скрытую цену: более широкое использование базы данных tempdb.

В чем еще проблема SNAPSHOT? Появляется *_Read Skew_* (also see link:https://habr.com/ru/company/otus/blog/501294/[habr]). Read skew возникает когда мы работаем с несколькими таблицами, содержание которых должно меняться согласованно.