== Spring Beans & Bean Factory

Ядром контейнера внедрения зависимостей в Spring служит интерфейс *_Bean Factory_*, который отвечает за управление компонентами *_Spring Beans_*, в том числе их зависимостями и жизненными циклами. Термин *_компонент Spring Веап_* употребляется в Spring для обозначения любого компонента, управляемого контейнером. Как правило, компоненты Spring Beans придерживаются на определенном уровне спецификации компонентов JavaBeans, хотя это совсем не обязательно, особенно если для связывания компонентов Spring Beans друг с другом предполагается применять внедрение зависимостей через конструктор.

Если в приложении требуется лишь _поддержка внедрения зависимостей_, то с контейнером внедрения зависимостей в Spring можно взаимодействовать через интерфейс BeanFactory. В этом случае в приложении необходимо создать экземпляр класса, реализующего интерфейс BeanFactory, и сконфигурировать его на основании сведений о компонентах Spriпg Beans и зависимостях. Как только это будет сделано, компоненты Spriпg Beans могут быть доступны в приложении через интерфейс BeanFactory для последующей обработки.

Компоненты Spring Beans можно идентифицировать в интерфейсе Bean Factory, и каждому компоненту Spring Bean может быть назначен *_идентификатор_*, *_имя_* или то и другое. Экземпляр компонента Spring Bean можно получить и без идентификатора или имени (это так называемый *_анонимный_* компонент Spring Bean) или как один компонент внутри другого компонента Spring Bean.

У каждого компонента Spring Bean имеется по крайней мере одно имя, но их может быть сколько угодно, причем дополнительные имена разделяются запятыми. Все имена после первого считаются псевдонимами того же самого компонента Spring Bean. Чтобы извлечь компоненты Spring Beans из интерфейса BeanFactory и установить отношения зависимости, можно воспользоваться их идентификаторами или именами.