=== ApplicationContext

Интерфейс *_ApplicationContext_* служит расширением интерфейса BeanFactory в Spring. Помимо услуг no внедрению зависимостей, интерфейс ApplicationContext предоставляет такие услуги, как транзакции и АОП, обработка событий в приложениях и пр. Рекомендуется взаимодействовать с Spring через интерфейс ApplicationContext.

Для конфигурирования с помощью разметки в формате XML необходимо объявить обязательное для приложения *_базовое пространство имен_*, предоставляемое в Spring. Кроме пространства имен *_beans_* в Spring представлены и другие. К их числу относится пространство имен *_context_* для конфигурирования интерфейса ApplicationContext, пространство имен *_аор_* для поддержки АОП и пространство имен *_tx_* для поддержки транзакций. Эти пространства имен описываются в соответствующих главах.

Чтобы воспользоваться поддержкой аннотаций в Spring при разработке приложения, необходимо объявить соответствующие дескрипторы в ХМL-файле конфигурации, как демонстрируется в приведенном ниже примере.

[source, xml]
----
<?xml version="l.0" encoding="UTF-8"?>

<beans xmlns="...">
  <context:component-scan base-package="com.gmail.konstantinovd">
    <context:exclude-filter type="assignable" expression="com.example.NotAService"/>
  </context:component-scan>
</beans>
----

Дескриптор *_<context: component-scan>_* сообщает Spring о необходимости просмотра исходного кода на предмет внедряемых компонентов *_SpringBeans_*, снабженных аннотациями *_@Component_*, *_@Controller_*, *_@Repository_* и *_@Service_*, а также поддерживающих аннотации *_@Autowired_* и *_@Inject_* в указанном пакете (и всех его подчиненных пакетах). В дескрипторе *_<context: component-scan_*> можно определить целый ряд пакетов, используя в качестве разделителя запятую, точку с запятой или пробел. А для более точного управления в этом дескрипторе поддерживается включение и исключение средств просмотра компонентов.

[source, xml]
----
<context:exclude-filter type="assignable" expression="com.example.NotAService"/>
----

Приведенный выше дескриптор сообщает Spring о необходимости пропуска классов, для которых был назначен тип, заданный в выражении (им может быть класс или интерфейс). Помимо исключающего фильтра, можно применять и включающий фильтр. В качестве критерия фильтрации в атрибуте type можно указать *_annotation_*, *_regex_*, *_assignable_*, *_aspectj_* или *_custom_* (с собственным классом фильтра, реализующим интерфейс _org.springframework.core.type.filter.TypeFilter_). Формат выражения в атрибуте *_expression_* зависит от заданного типа.