=== Notes

- [Spr] *N+1 Hibernate problem*: link:https://hackernoon.com/3-ways-to-deal-with-hibernate-n1-problem[hackernoon] +
В Hibernate есть *_FetchType.LAZY_*, и мы можем поставить ее на коллекцию. Если нам нужна эта коллекция - и мы ее запрашиваем в LAZY формате (не пришла в запросе, но потом вы решили проитерироваться по коллекции или вызвать у нее метод `size()`) - то каждая дочерняя сущность будет запрашиваться отдельным запросом, и так мы получаем N+1 запрос. +
Этого можно избежать, проставив либо `@BatchSize(size = 10)`, либо `@Fetch(FetchMode.SUBSELECT)`:
[source, java]
----
@OneToMany(fetch = FetchType.LAZY, mappedBy = "author")
@BatchSize(size = 10)
private Set<Book> books;
----

- [JC] *_Hashcode_* - Возвращает int, в теории может быть и негативным, но на практике такого обычно нет. По дефолту возвращает адрес объекта в памяти, поэтому объекты по дефолту имеют разный хэшкод.
- [JC] *_String hashcode_* - хэшкод стринга кэшируется, поэтому они очень удобны в качестве ключей.
- Дефолтный FetchType: *_FetchType.LAZY_* (для @ManyToMany, @ManyToOne, etc)