=== Notes 3

- Вы можете использовать SpringData репозитории для доступа к монге: +
_org.springframework.data.mongodb.repository.*MongoRepository* extends **PagingAndSortingRepository**_
- CrudRepository/JpaRepository под собой используют в том числе *_CriteriaQueryApi_*.
- ParallelStream - работает ток если несколько ядер. Фактически применение параллельных потоков сводится к тому, что данные в потоке будут разделены на части, каждая часть обрабатывается на отдельном ядре процессора, и в конце эти части соединяются, и над ними выполняются финальные операции. При использовании стримов используется ForkJoinPool, и чем больше элементов будет в стриме - тем больше потоков будет создано. Чем больше данных, тем сложнее сначала разделять данные, а потом их соединять. Поэтому 1) мало элементов - преимущества теряются, 2) много элементов - много разделений на ядра проца - преимуществ тоже не будет, проще обычный стрим заюзать. +
Ссыль: link:https://metanit.com/java/tutorial/10.9.php[metaint]
- Вызов неаннотированного метода из *_@Transactional_*-метода: +
link:https://overcoder.net/q/78621/%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%BE%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-%D0%B2%D1%8B%D0%B7%D1%8B%D0%B2%D0%B0%D1%8E%D1%89%D0%B8%D0%B9-%D0%B4%D1%80%D1%83%D0%B3%D0%BE%D0%B9-%D0%BC%D0%B5%D1%82%D0%BE%D0%B4-%D0%B1%D0%B5%D0%B7-%D0%B0%D0%BD%D0%BD%D0%BE%D1%82%D0%B0%D1%86%D0%B8%D0%B8-transactional[transactional-method-calls-another-method-without-transactional]