=== Notes 5

- Полезный сайт с вопросами к собесам - link:https://itsobes.ru/JavaSobes/tags/mnogopotochnost/[itsobes.ru]

===== Почему в java используются красно-черные деревья а не AVL?

link:https://ru.wikipedia.org/wiki/%D0%9A%D1%80%D0%B0%D1%81%D0%BD%D0%BE-%D1%87%D1%91%D1%80%D0%BD%D0%BE%D0%B5_%D0%B4%D0%B5%D1%80%D0%B5%D0%B2%D0%BE[wikipedia], link:https://igororlov92.livejournal.com/26151.html[livejournal]

Так как в идеально сбалансированном дереве (AVL) много ресурсов тратится на поддержание сбалансированности, рекомендуется использовать его в ситуации, когда вставка/удаление происходит существенно реже считывания. Красно-черные деревья, наоборот, тратят меньше ресурсов на поддержание сбалансированности (хотя здесь тоже есть перебалансировка), и их лучше использовать, когда вставка и чтение проиходят примерно с одинаковой частотой. Именно на основе красно-черных деревьев основываются большинство реализаций set и map из STL. +
При том же количестве листьев красно-чёрное дерево может быть выше АВЛ-дерева, но не более чем в 1.388 раз. Поскольку красно-чёрное дерево, в худшем случае, выше, поиск в нём медленнее, но проигрыш по времени не превышает 39%. Зато оно не тратит так много времени на перебалансировку.

