spring:
  datasource:
    username: sa
    password: pass
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 100
  h2:
    console:
      enabled: true
logging:
  level:
    liquibase: INFO
