spring:
  datasource:
    url: jdbc:h2:file:C:/Users/d.m.konstantinov/DRIVE/PROJECTS/my_own_projects/embedded-db/p65_presisted_object_and_hibernate_properties
    username: sa
    password: pass
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 100
  liquibase:
    change-log: classpath:p65_presisted_object_and_hibernate_properties/changelog.yaml
  h2:
    console:
      enabled: true
logging:
  level:
    liquibase: INFO
