== Выталкивание контекста хранения - session flush(). FlushMode.COMMIT/AUTO

По умолчанию Hibernate выталкивает контекст и синхронизирует изменения с БД при окончании транзакции. JPA позволяет реализациям выполнять синхронизацию контекста хранения в другие моменты, если они того желают.

Hibernate как реализация JPA выполняет синхронизацию:

- Во время подтверждения присоединенной системной транзакции JTA;
- Dо время явного вызова flush() приложением;
- Перед выполнением запроса, выполненного с помощью интерфейса `javax.persistence.Query` или другого подобного Hibernate API (мы не имеем в виду поиск с помощью `find()/findById()`)

Это поведение можно изменить с помощью настройки FlushModeType объекта EntityManager или проперти `"org.hibernate.flushMode"` которое может принимать 2 значения - `"AUTO(default)/COMMIT"`.

Рассмотрим пример. Пусть внутри транзакции происходит сохранение класса link:../../hibernate-learning/src/main/java/ch6_hibernate/p288_SessionFlushing/entity/User.java[User.java], перемежаясь с другими запросами +
*_See:_* link:../../hibernate-learning/src/main/java/ch6_hibernate/p288_SessionFlushing/SessionFlushingScheduler.java[SessionFlushingScheduler.java]:

[source, java]
----
public void process() {
    userRepository.deleteAll();
    User user = new User().setName("Viktor");
    User user2 = new User().setName("Grigory");
    User user3 = new User().setName("Pavel");
    transactionalProcessor.runInNewTransaction(() -> {
        userRepository.save(user);
        userRepository.save(user2);
        // ЛОГИ HIBERNATE - insert user-ов еще не произошел

        var notExistingId = user.getId().add(user2.getId());
        var userOptional = userRepository.findById(notExistingId);
        // ЛОГИ HIBERNATE - insert user-ов все еще не произошел
        // т к метод типа find/findById

        var elderUsers = userRepository.findByAgeGreaterThan(17);
        // ЛОГИ HIBERNATE - insert произошел - метод типа query
        // Если включен FlushMode.COMMIT то insert-ов не происходит

        userRepository.save(user3);
        // ЛОГИ HIBERNATE - insert user-а еще не произошел

        var usersNumber = userRepository.countUsers();
        // ЛОГИ HIBERNATE - произошел insert user-а из-за выполнения @Query
        // Если включен FlushMode.COMMIT то insert не происходит

        userRepository.save(user4);
        jdbcTemplate.queryForList(
             "select * from users where name = Grigory");
        // jdbcTemplate не действует в контексте hibernate
        // insert user не происходит
    });
}
----

Если у нас FlushMode = AUTO (по умолчанию), то мы не будем flush-ить сессию, если выполняются методы типа `findById()`. В случае же более хитрых методов `findByAgeGreaterThan()` или методов, аннотированных *_@Query_*, по типу `countUsers()`, происходит сброс сессии и сохранение user-ов в БД. К слову, вызовы *_jdbcTemplate_* на сброс сессии Hibernate не влияют.

Если же мы установим в link:../../hibernate-learning/src/main/java/ch6_hibernate/p288_SessionFlushing/SessionFlushingMain.java[SessionFlushingMain.java] пропертю `org.hibernate.flushMode` в значение `COMMIT`:
[source, java]
----
public static void main(String[] args) {
    CommonUtils.setProperties("p288_SessionFlushing");
    System.setProperty("org.hibernate.flushMode", "COMMIT");
    SpringApplication.run(SessionFlushingMain.class, args);
}
----

то мы получим интересную картину - вся сессия целиком будет сброшена только в конце транзакции, несмотря на вызовы *_@Query_*. Исключением является объекты, которые требуют немедленного сохранения - см. пример про вставку ID-шников - link:p279_insert_id_order.adoc[] -
link:../../hibernate-learning/src/main/java/ch6_hibernate/p279_1_insert_id_order/InsertIdOrderScheduler.javaa[InsertIdOrderScheduler.java].