== PasswordEncoder

*Content:*

- 1. Понимание контракта PasswordEncoder
- 2. Примеры реализации интерфейса PasswordEncoder
  * 2.1 Как работает SHA-512

=== 1. Понимание контракта PasswordEncoder

Поскольку, как правило, система не обрабатывает пароли в виде plaintext, они шифруются, чтобы затруднить их чтение и кражу. Для этого Spring Security определяет контракт *PasswordEncoder*.

- В процессе аутентификации _PasswordEncoder_ проверяет пароль с помощью метода `encode()`.
- Каждая система хранит пароли в зашифрованном виде, зачастую - хешированными. PasswordEncoder также может кодировать пароли, используя метод `encode()`.
- Методы интерфейса `encode()` и `match()` являются частями одного и того же контракта и тесно связаны друг с другом, потому что от способа шифровки пароля зависит и способ проверки пароля.

Рассмотрим интерфейс _PasswordEncoder_, который имеет два абстрактных и один дефолтный методы:
[source, java]
----
public interface PasswordEncoder {

    String encode(CharSequence rawPassword);

    boolean matches(CharSequence rawPassword, String encodedPassword);

    default boolean upgradeEncoding(String encodedPassword) {
        return false;
    }
}
----

- Цель метода *_encode()_* — вернуть трансформацию строки. В Spring Security он используется для шифрования пароля или вычисления хэша от него.
- После этого вы можете использовать метод *_match()_*, чтобы проверить, соответствует ли зашифрованная строка raw-паролю. Используется в процессе аутентификации для валидации пароля.
- Третий метод, *_upgradeEncoding()_*, возвращает true если пароль должен быть зашифрован еще раз для лучшей безопасности, иначе false (по дефолту не шифруем повторно). Так можно рекурсивно шифровать пароль несколько раз, если написать соответствующую реализацию _PasswordEncoder_.

=== 2. Примеры реализации интерфейса PasswordEncoder

Методы _match()_ и _encode()_ должны соответствовать контракту - строка, возвращаемая методом _encode()_, всегда должна поддаваться проверке с помощью метода _match()_ того же самого _PasswordEncoder_.

Наиболее простая реализация _PasswordEncoder_ обрабатывает пароли в виде простого текста, т.е. не выполняет никакого шифрования. Это именно то, что делает экземпляр _NoOpPasswordEncoder_, предоставляемый Spring Security. Мы бы написали его реализацию как-то так:
[source, java]
----
public class PlainTextPasswordEncoder implements PasswordEncoder {
    @Override
    public String encode(CharSequence rawPassword) {
        // мы не кодируем пароль а просто возвращаем его как есть
        return rawPassword.toString();
    }

    @Override
    public boolean matches(CharSequence rawPassword, String encodedPassword) {
        return rawPassword.equals(encodedPassword); // equals двух строк
    }
}
----

=== 2.1 Как работает SHA-512

Простая реализация _PasswordEncoder_, использующая алгоритм хэширования SHA-512 (каждая 16-ричная цифра оказыввает влияние на итог алгоритма - см https://ru.wikipedia.org/wiki/%D0%9B%D0%B0%D0%B2%D0%B8%D0%BD%D0%BD%D1%8B%D0%B9_%D1%8D%D1%84%D1%84%D0%B5%D0%BA%D1%82[лавинный эффект]), может выглядеть следующим образом:
[source, java]
----
public class Sha512PasswordEncoder implements PasswordEncoder {
    @Override
    public String encode(CharSequence rawPassword) {
        return hashWithSHA512(rawPassword.toString());
    }

    @Override
    public boolean matches(CharSequence rawPassword, String encodedPassword) {
        // Чтобы проверить raw password метод matches() хеширует его
        // и сравнивает с хэшем действительного пароля
        String hashedPassword = encode(rawPassword);
        return encodedPassword.equals(hashedPassword);
    }

    private String hashWithSHA512(String input) {
        StringBuilder result = new StringBuilder();
        try {
            // закодировали пароль в SHA-512
            // (длина 16 байт или 32 шестнадцатеричных цифры)
            MessageDigest md = MessageDigest.getInstance("SHA-512");
            byte [] digested = md.digest(input.getBytes());
            // записываем эти 32 шестнадцатеричных цифры как строку
            for (int i = 0; i < digested.length; i++) {
                result.append(Integer.toHexString(0xFF & digested[i]));
            }
        } catch (NoSuchAlgorithmException e) {
            throw new RuntimeException("Bad algorithm");
        }
        return result.toString();
    }
}
----
По факту мы даже не декодируем пароль (мы не можем это сделать) - мы просто смотрим, будет ли хэш raw password равен хэшу действительного пароля. Хеш не является шифрованием - его нельзя расшифровать обратно к исходному тексту, это односторонняя криптографическая функция. Соответственно расшифровка SHA256 невозможна (см link:https://siterost.net/page/sha256-online-hash-generator[sha256-online-hash-generator]). Но число вариантов возможных паролей теоретически бесконечно, а вот число hash всегда конечное, хоть и очень большое. Провести обратное преобразование и получить пароль непосредственно из хеша невозможно в принципе, даже если очистить его от соли. Однако можно решить сходную задачу: сгенерировать пароль с таким же hash. Из-за эффекта коллизии задача упрощается: возможно, ты никогда не узнаешь настоящий пароль, но найдешь совершенно другой, дающий после хеширования по этому же алгоритму такой же хэш (см link:https://blockchain24.pro/rasshifrovka-sha256-onlajn-dekorder-heshej-decoder-online[blockchain24.pro]).
