== DelegatingPasswordEncoder и стратегии шифрования

Бывает так, что для проверки паролей надо использовать различные кодировщики паролей. Например, приложение с какой-то версии меняет алгоритм шифрования - но ведь старые пользователи-то остаются, для них нужно использовать старое шифрование. *_DelegatingPasswordEncoder_* позволяет делегировать сопоставление и шифрование различным реализациям _PasswordEncoder_.

До Spring Security 5.0 приложения могли использовать только один алгоритм кодирования паролей. Стандартной реализацией был _StandardPasswordEncoder_ (SHA-256), который можно было переопределить. Но версия 1.5 предоставила возможность делегировать шифрование паролей. +
*_See_* link:https://www.baeldung.com/spring-security-5-password-storage[baeldung] - а также там сказано про миграцию паролей

И также появился фабричный метод, который возвращает *_DelegatingPasswordEncoder_*:
[source, java]
----
PasswordEncoderFactories.createDelegatingPasswordEncoder()
----

Например, так выглядит хэш пароля, захешированный с помощью bcrypt в Spring Security 5.0 - он содержит префикс *{bcrypt}*. То же касается и *{noop}* и *{pbkdf2}*:
----
{bcrypt}$2b$12$FaLabMRystU4MLAasNOKb.HUElBAabuQdX59RWHq5X.9Ghm692NEi
{noop}password
{pbkdf2}5d923b44a6d129f3ddf3e3c8d29412723dcbde72445e8ef6bf3b508fbf17fa4ed4d6b99ca763d8dc
----

Если хэш пароля не имеет префикса, используется кодировщик по умолчанию. По дефолту это _StandardPasswordEncoder_. Это обеспечивает совместимость с предыдущими версиями SS.

Допустим нам надо поддерживать:

- bcrypt as our new default
- scrypt as an alternative
- SHA-256 as the currently used algorithm

Тогда конфигурация может выглядеть как-то так (link:https://www.baeldung.com/spring-security-5-password-storage[baeldung]):
[source, java]
----
@Bean
public PasswordEncoder delegatingPasswordEncoder() {
    PasswordEncoder defaultEncoder = new StandardPasswordEncoder();
    Map<String, PasswordEncoder> encoders = new HashMap<>();
    encoders.put("bcrypt", new BCryptPasswordEncoder());
    encoders.put("scrypt", new SCryptPasswordEncoder());

    DelegatingPasswordEncoder passworEncoder = new DelegatingPasswordEncoder(
      "bcrypt", encoders);
    passworEncoder.setDefaultPasswordEncoderForMatches(defaultEncoder);

    return passworEncoder;
}
----
Первый аргумент в конструкторе _DelegatingPasswordEncoder_ - это кодировщик, который будет использоваться при вызове метода `DelegatingPasswordEncoder.encode(CharSequence rawPassword)`. Используется только один кодировщик, его нельзя поменять. А вот метод `matches()` может делегировать проверку в зависимости от префикса нужному кодировщику. Метод `setDefaultPasswordEncoderForMatches` позволяет установить дефолтный кодировщик, который будет вызываться, если вызвать `matches(password, null)` или с любым другим _prefixEncodedPassword_ которого нет в _DelegatingPasswordEncoder_. Если же дефолтный кодировщик не назначен, метод `matches()` вызовет *_UnmappedIdPasswordEncoder_*, который выкинет _IllegalArgumentException_.





